### ISSUE TITLE
Raspberry pi 3 display

### ISSUE THREAD

**Issue by rohanki** [erikboto/monark-ant#7]
Hi there. Firstly, thankyou again for all your work on this project! I find it extremely useful.
I have a raspberry pi 3, and I'm having problems using your compiled images using the official 7" touch screen.
FTMS v1 - after boot, alternating between solid black and solid grey screen, no buttons appear for manual power control.
v3 rc3 - no GUI, boots to CLI login prompt.
Hoping you can help?
Thanks again!

**Comment by erikboto** [comment]
Hi,

During the first early versions it did show a very basic GUI. But this was removed at some point since I had an idea of making a more nice UI that was separate from the small daemon that handle the communication with the bike. But since I didn't really need that kind of GUI myself, and non of the other users I had any contact with seemed to need one, it sort of got forgotten.

However, I'm currently working on creating a small iOS app that can monitor/control the bike, and then it would probably be quite quick to also add a local GUI that you could use.

What model do you have, and how do you typically use it? That would help me understand what you'd like in a GUI so that I add the right features first.

If you're into Zwift or other simulation apps, the idea is that you could use the iOS app to shift "virtual gears" if you run in simulation mode, or target power/kp if not. For myself I've also added small pushbuttons sticking up through the handlebar tape for shifting or adjusting target power depending on if you're running a simulation or not. But most people using it probably won't bother with that but maybe they'll find the iOS app useful.

**Comment by rohanki** [comment]
Ah right!
I really liked the basic GUI in your early versions as an option to have a fully manual workout if I wanted, but also liked the ability to quickly drop/add some resistance mid .erg from golden cheetah. I have a Raspberry Pi 3B+ with the 7" touch screen mounted on an LC6 just under the 'note holder' or whatever it's supposed to be in front of the handlebars.
But an iOS app would also be just as useful. I myself use Golden Cheetah and ERG workouts on zwift most of the time.

The buttons sound interesting! is that functionality already in the pi images? if so, which GPIO's are they connected to?

**Comment by erikboto** [comment]
Ok, then I know what to aim for. You were probably the only one using that GUI, but it shouldn't be more than a few hours to get something up again so I hope I can get that done shortly. The iOS app is probably a bit further away since it's my first venture into app-land and I'll have to get the whole AppStore process figured out before anyone else can use it.

My first attempt was to connect simple buttons directly to GPIO:s on the Pi, but I had to many "ghost pushes" due to electric interference that I gave up that approach. Using some additional R/C-filtering it got better, but was still too annoying. It can probably be done though, but in my case I just connected the buttons to an Adafruit Trinket M0 instead, which I connect to the Pi via USB instead, and then there's a simple python service that read clicks and forward to the monark-ant program.

Let me know if you intend to do something similar, then I can help you with either the Trinket M0-code, or describe how you can send the commands to monark-ant on the Pi via DBus if you want to create your own solution using Pi GPIO.

I haven't used e.g. Zwift on a smart trainer, but I expect that the "simulation experience" is much better there than it is with this solution. But I figured it might be better than nothing, and with some experimenting with the parameters of how much a "virtual gear" should be it might give a decent feeling.

The button code is not in the currently available version, but I'll push an updated image in a day or so since I just added the ability for e.g. Zwift/FulGaz etc to control the grade via FTMS when used in simulation mode.

**Comment by rohanki** [comment]
Thanks so much - I didn't realise I was the only one using your original GUI!
THanks for the info about the button input - at this point I think being able to use the pi's touch screen will be good enough..

Thanks again - its so appreciated!

**Comment by erikboto** [comment]
I've created a (quite ugly) GUI that should be able to replace the old one for you. You can download a complete image here: http://linode.unixshell.se/monark/image-monark-ftms-ui-rpi3.zip

The "Mode" buttons change if you want to set a Kp or Power, and the currently active one shows in bold font.

You can increase/decrease in two step sizes, which is as following depending on current mode:

inc lots = +100 W or +2.0 kp
inc = +5 W or +0.3 kp
dec lots = -100 W or -2.0 kp
dec = -5 W or -0.3 kp

If you run e.g. Zwift in simulation mode it will be in a special "kp mode", where the kp sent to the monark will be a sum of the grade from Zwift + an offset that you increase/decrease using the buttons.

Let me know if this works for you. I'll probably polish the GUI a bit in the future and will include it as part of the standard images, but I wanted to get something quick out first.

**Comment by rohanki** [comment]
Thanks so much!
Unfortunately that image still gets stuck at the login prompt. It also looks like it doesn't connect to the bike (no LED flash on the USB->RS232 adapter).

Thanks again

**Comment by erikboto** [comment]
Hmm, seems like it's an issue where it waits a long time for network connection before starting some services. I didn't catch it when testing here since I only tried with a network connection active. It should start after a couple of minutes anyway though, but it's an annoying delay.

You can either remove the After=network-online.target row in /lib/systemd/system/mosquitto.service, or wait a while and I'll upload a new image shortly.

**Comment by erikboto** [comment]
This image should work without any delay: http://linode.unixshell.se/monark/image-monark-ftms-ui-rpi3_v2.zip

**Comment by rohanki** [comment]
That works perfect!
Thankyou so much!!!
